services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: gameuser
      POSTGRES_PASSWORD: gamepass
      POSTGRES_DB: gamedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://gameuser:gamepass@db/gamedb
      REDIS_URL: redis://redis:6379
      JWT_SECRET_KEY: my-secret-key
    depends_on:
      - db
      - redis

volumes:
  postgres_data: